title: Emile J. Wilcox
logo: (https://yt3.ggpht.com/cEpMzdCyUsdU4Mg-VSrj5XoZV765MkwnZwgEy9WOiQ7tWQ-IH_DcxrJOz1tY39GJ68unsDziMQ=s176-c-k-c0x00ffffff-no-rj)
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
